//
// ============LICENSE_START=======================================================
//  Copyright (C) 2016-2018 Ericsson. All rights reserved.
// ================================================================================
// This file is licensed under the CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE
// Full license text at https://creativecommons.org/licenses/by/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (sven.van.der.meer@ericsson.com)
//

== The APEX Monitoring Client
The standard way to use the APEX Monitoring Client is via an installation of the __war__ file on a webserver.
However, the Monitoring Client can also be started via command line.
This will start a Grizzly webserver with the __war__ deployed.
Access to the Monitoring Client is then via the provided URL 

On UNIX and Cygwin systems use:

- `apexApps.sh eng-monitoring` - simply starts the webserver with the Monitoring Client

On Windows systems use:

- `apexApps.bat eng-monitoring` - simply starts the webserver with the Monitoring Client


The option `-h` provides a help screen with all command line arguments.

[source%nowrap,sh]
----
usage: org.onap.policy.apex.client.monitoring.rest.ApexMonitoringRestMain [options...]
-h,--help                        outputs the usage of this command
-p,--port <PORT>                 port to use for the Apex Services REST calls
-t,--time-to-live <TIME_TO_LIVE> the amount of time in seconds that the server will run for before terminating
----

If the Monitoring Client is started without any arguments the final messages will look similar to this:

[source%nowrap,sh]
----
Apex Services REST endpoint (ApexMonitoringRestMain: Config=[ApexMonitoringRestParameters: URI=http://localhost:18989/apexservices/, TTL=-1sec], State=READY) starting at http://localhost:18989/apexservices/ . . .
Sep 05, 2018 11:26:20 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [localhost:18989]
Sep 05, 2018 11:26:20 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Apex Services REST endpoint (ApexMonitoringRestMain: Config=[ApexMonitoringRestParameters: URI=http://localhost:18989/apexservices/, TTL=-1sec], State=RUNNING) started at http://localhost:18989/apexservices/
----

The last line states the URL on which the Monitoring Client can be accessed.
The example above stated `http://localhost:18989/apexservices`.
In a web browser use the URL `http://localhost:18989`.

