//
// ============LICENSE_START=======================================================
//  Copyright (C) 2016-2018 Ericsson. All rights reserved.
// ================================================================================
// This file is licensed under the CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE
// Full license text at https://creativecommons.org/licenses/by/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (sven.van.der.meer@ericsson.com)
//

== Eclipse Plugin: Checkstyle

This plugin integrates link:http://checkstyle.sourceforge.net/[Checkstyle] into Eclipse.
It will check your code and flag any checkstyle issues as warnings in the code.

Available from the Eclipse Marketplace.
In Eclipse Help->Eclipse Marketplace... and type "Checkstyle".
Select "Checkstyle Plug-in" when the search returns and install it.
Note that "Checkstyle Plug-in" may not be the first result in the list of items returned.

For APEX, the ONAP checkstyle rules do apply.
The configuration is part of the ONAP parent.
See link:https://git.onap.org/oparent/plain/checkstyle/src/main/resources/onap-checkstyle/[ONAP Git] for details and updates.
All settings for checkstyle are already part of the code (POM files).

