//
// ============LICENSE_START=======================================================
//  Copyright (C) 2016-2018 Ericsson. All rights reserved.
// ================================================================================
// This file is licensed under the CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE
// Full license text at https://creativecommons.org/licenses/by/4.0/legalcode
// 
// SPDX-License-Identifier: CC-BY-4.0
// ============LICENSE_END=========================================================
//
// @author Sven van der Meer (sven.van.der.meer@ericsson.com)
//

== Configure the Jython Executor

WARNING: The Jython plugin allows you to use extra Python packages installed with *_pip_* or at
startup using the *_setup.py_* or *_build_py.py_* configuration files. Extra modules must be checked
by developers prior to installation to ensure that they are not malicious and do not exploit the
Python Path Traversal vulnerability. the Jython plugin does *NOT* check extra modules for security
vulnerabilities.


The Jython executor is added to the configuration as follows:

[source%nowrap,json]
----
"engineServiceParameters":{
  "engineParameters":{
    "executorParameters":{
      "JYTHON":{
        "parameterClassName" :
        "org.onap.policy.apex.plugins.executor.jython.JythonExecutorParameters"
      }
    }
  }
}
